### PR TITLE
Fix Julia 0.6 deprecations

### PR DESCRIPTION
**Pull request by nalimilan**
Remaining warnings come from NullableArrays (and are fixed on its master
branch).

### CODE REVIEW

**Comment by nalimilan** [comment]
Tests passed on 0.5.

**Comment by ararslan** [comment]
Do you want to `s/sub/view/` while you're at it? That should get things passing on 0.6 I think.

**Comment by cjprybol** [comment]
👍

**Comment by nalimilan** [comment]
OK to merge?

@andreasnoack The change to compute reserved words should be useful for your PR (adapting the list is not enough).

**Comment by andreasnoack** [comment]
Yes. I saw your fancy regex and plan to steal it. It is much better than the hack I implemented.

**Comment by nalimilan** [comment]
Actually, I had forgotten I made a PR for it: https://github.com/JuliaStats/DataFrames.jl/pull/1165.

**Pull request merged**
