### PR TITLE
Enable builds on nightlies, add Julia 0.6 badge

### PR DESCRIPTION
**Pull request by nalimilan**
Will merge if tests pass to check whether Documenter manual deployment works.

### CODE REVIEW

**Comment by nalimilan** [comment]
Ah, tests fail due to the DataArrays issue. I think the reason why the manual wasn't deployed is not because of errors (https://github.com/JuliaData/DataTables.jl/pull/71#issuecomment-304584640), but because we don't build it on nightlies.

**Comment by ararslan** [comment]
> Ah, tests fail due to the DataArrays issue

What does DataArrays have to do with this package? I'm confused.

**Comment by nalimilan** [comment]
Yes, that's really confusing, but one our dependencies (probably DataStreams, needed for the `readtable` deprecation) requires DataFrames. And since DataArrays does not even load, it breaks everything.

**Comment by ararslan** [comment]
> And since DataArrays does not even load

._.

**Comment by quinnj** [comment]
Yeah, the current dependency situation is rather unfortunate. Fortunately, I have branches where the dependencies are much cleaner (i.e. DataStreams only depends on Nulls & WeakRefStrings, CSV only depends on DataStreams, Nulls, WeakRefStrings, DataTables only depends on DataStreams, Nulls, WeakRefStrings, etc.). Unfortunately, I'm falling in love w/ `NamedTuple`s, and that's not even merged yet :S. I'm going to try and get everything cleaned up on my branches over the next week and push everything up. It's been a fun couple weeks of diving deep into the performance characteristics of DataStreams and some codegen issues of Union{T, Null}, but I think I'm ready to actually settle on some code and push.

**Comment by nalimilan** [comment]
OK, Documenter manual is now up to date!

**Pull request merged**
