### PR TITLE
rm duplicate functionality of base.vcat for void vectors

### PR DESCRIPTION
**Pull request by cjprybol**
https://github.com/JuliaData/DataTables.jl/pull/7#discussion_r102299221

### CODE REVIEW

**Review by ararslan — APPROVED** [review]
Nice, thanks 🙂

**Comment by ararslan** [comment]
Huh. `hcat` ambiguity error on Linux nightly, doesn't show up on Windows. Is this a preexisting condition? cc @nalimilan

**Comment by cjprybol** [comment]
same error on the other (unrelated) pull request Tony asked for https://travis-ci.org/JuliaData/DataTables.jl/jobs/203944131#L683

**Comment by ararslan** [comment]
Weird.

**Pull request merged**
